#!/usr/bin/env python3
"""Compare 64-bit and 32-bit snapshots of synthetic completion-cache products.

This measures payload allocation, RSS, saving and restoring products using
the existing runtime's SIMD range predicate. It does not exercise scheduler
cache identity, CUDA graph storage, model inference or a live worker. The
conversion-only mode receives locally generated, already bounded values.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import statistics
import subprocess
import tempfile


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--runtime', required=True, type=Path)
    p.add_argument('--cpu', required=True, type=int)
    p.add_argument('--repetitions', type=int, default=7)
    p.add_argument('--output', required=True, type=Path)
    args = p.parse_args()
    if args.repetitions < 1 or args.cpu not in os.sched_getaffinity(0):
        p.error('positive repetitions and an allowed CPU are required')
    repo = Path(__file__).resolve().parents[2]
    rt = args.runtime.resolve()
    env = {k: v for k, v in os.environ.items() if not k.startswith(('SHIELDED_', 'LD_'))}
    env.update(OMP_NUM_THREADS='1', OMP_DYNAMIC='FALSE')
    rows = []
    with tempfile.TemporaryDirectory(prefix='completion-storage-') as temp:
        binary = Path(temp) / 'probe'
        subprocess.run(['c++', '-O2', '-std=c++17', '-Wall', '-Wextra', '-Werror',
            '-I' + str(repo / 'wasm/ggml-shielded'), str(Path(__file__).with_suffix('.cpp')),
            '-L' + str(rt), '-L' + str(rt / 'backends'), '-l:libggml-shielded.so',
            '-l:libggml.so.0', '-l:libggml-base.so.0', '-Wl,-rpath-link,' + str(rt),
            '-o', str(binary)], check=True, timeout=60)
        for values, groups in [(96, 64), (17408, 48), (17408*16, 48), (17408*64, 8)]:
            samples = {mode: [] for mode in ['wide', 'narrow', 'checked']}
            for repeat in range(args.repetitions):
                order = list(samples)
                order = order[repeat % 3:] + order[:repeat % 3]
                if repeat % 2:
                    order.reverse()
                for mode in order:
                    result = subprocess.run(['bwrap', '--unshare-all', '--ro-bind', str(rt), '/rt',
                        '--ro-bind', str(binary), '/probe', '--proc', '/proc', '--dev', '/dev',
                        '/rt/ld-linux-x86-64.so.2', '--library-path', '/rt:/rt/backends', '/probe',
                        mode, str(values), str(groups), '30'], env=env, text=True, capture_output=True,
                        check=True, timeout=60, preexec_fn=lambda: os.sched_setaffinity(0, {args.cpu}))
                    value = json.loads(result.stdout)
                    assert value['exact'] and value['mode'] == mode
                    samples[mode].append(value)
            row = dict(values=values, groups=groups, samples=samples)
            for mode, entries in samples.items():
                row[mode] = {key: statistics.median(v[key] for v in entries) for key in entries[0]
                             if key not in ['mode', 'simd', 'values', 'groups', 'loops', 'exact']}
            for mode in ['narrow', 'checked']:
                row[mode]['cycle_change_pct'] = 100 * (row[mode]['cycle_us'] / row['wide']['cycle_us'] - 1)
            rows.append(row)
            print(json.dumps({k: v for k, v in row.items() if k != 'samples'}), flush=True)
    args.output.write_text(json.dumps(dict(scope=__doc__, cpu=args.cpu, repetitions=args.repetitions,
        method='Rotating/reversed mode order in fresh isolated processes pinned to one CPU. Median across process means; each process performs 30 save/restore cycles. Every snapshot is checked exactly with destination guards outside the measured intervals. No malloc_trim.',
        caveat='Counts are synthetic payload controls, not measured model cache occupancy. Input keys, map metadata, scheduling, CUDA work and verification latency are excluded. RSS includes allocator effects. Narrowing receives valid balanced-field values generated by the probe; no security validation is removed from a runtime.',
        source_sha256=hashlib.sha256(Path(__file__).with_suffix('.cpp').read_bytes()).hexdigest(),
        runtime_sha256=hashlib.sha256((rt / 'backends/libggml-shielded.so').read_bytes()).hexdigest(),
        summary=rows), indent=2) + '\n')


if __name__ == '__main__':
    main()
