import { createPublicClient, http, fallback } from "viem";
import { base } from "viem/chains";
const c = createPublicClient({ chain: base, transport: fallback(["https://base-rpc.publicnode.com","https://mainnet.base.org"].map(u=>http(u))) });
const bookAbi = [{ type: "function", name: "all", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32[]" }, { type: "address[]" }] }];
const [keys, values] = await c.readContract({ address: "0xab214342d5A490150A4A977063A2f88E21F80907", abi: bookAbi, functionName: "all" });
let A; keys.forEach((kh,i)=>{let k="";for(let b=2;b<kh.length;b+=2){const ch=parseInt(kh.slice(b,b+2),16);if(!ch)break;k+=String.fromCharCode(ch);}if(k==="deployments")A=values[i];});
const TUPLE = [["id","bytes32"],["owner","address"],["appRef","string"],["ports","string"],["configCid","string"],["gpuMilli","uint16"],["cpuMilli","uint16"],["appPort","uint32"],["isPublic","bool"],["active","bool"],["createdAt","uint64"],["rate","uint256"],["balance6","uint256"],["spent6","uint256"],["runner","bytes32"],["runnerOperator","address"],["leaseUntil","uint64"]].map(([name,type])=>({name,type}));
const abi=[{type:"function",name:"count",stateMutability:"view",inputs:[],outputs:[{type:"uint256"}]},{type:"function",name:"getPage",stateMutability:"view",inputs:[{type:"uint256"},{type:"uint256"}],outputs:[{type:"tuple[]",components:TUPLE}]}];
const n=Number(await c.readContract({address:A,abi,functionName:"count"}));
const rows=[]; for(let s=0;s<n;s+=50) rows.push(...await c.readContract({address:A,abi,functionName:"getPage",args:[BigInt(s),50n]}));
const t=rows.find(d=>d.id.toLowerCase().startsWith("0x5c2dcc4b6e"));
console.log(JSON.stringify({block:Number(await c.getBlockNumber()),id:t.id.slice(0,12),active:t.active,balance6:String(t.balance6),spent6:String(t.spent6),rate:String(t.rate),leaseUntil:String(t.leaseUntil),runner:t.runner.slice(0,12),runnerOperator:t.runnerOperator,appRef:t.appRef}));
