import { createPublicClient, http, fallback } from "viem";
import { base } from "viem/chains";
const c = createPublicClient({ chain: base, transport: fallback(["https://base-rpc.publicnode.com","https://mainnet.base.org"].map(u=>http(u))) });
const TUPLE = [["id","bytes32"],["owner","address"],["appRef","string"],["ports","string"],["configCid","string"],["gpuMilli","uint16"],["cpuMilli","uint16"],["appPort","uint32"],["isPublic","bool"],["active","bool"],["createdAt","uint64"],["rate","uint256"],["balance6","uint256"],["spent6","uint256"],["runner","bytes32"],["runnerOperator","address"],["leaseUntil","uint64"]].map(([name,type])=>({name,type}));
const abi = [{type:"function",name:"count",stateMutability:"view",inputs:[],outputs:[{type:"uint256"}]},{type:"function",name:"getPage",stateMutability:"view",inputs:[{type:"uint256"},{type:"uint256"}],outputs:[{type:"tuple[]",components:TUPLE}]}];
const A = "0x0A7dE5D205c10B812AbaF0b89f3A243466bCEe01";
const n = Number(await c.readContract({address:A,abi,functionName:"count"}));
const rows = [];
for (let s=0;s<n;s+=50) rows.push(...await c.readContract({address:A,abi,functionName:"getPage",args:[BigInt(s),50n]}));
const now = Math.floor(Date.now()/1000);
const live = rows.filter(d=>d.active && Number(d.leaseUntil)>now);
const queued = rows.filter(d=>d.active && Number(d.rate)>0 && Number(d.balance6)>=Number(d.rate) && Number(d.leaseUntil)<=now);
console.log("leased:", live.map(d=>`${d.id.slice(0,10)} gpu=${d.gpuMilli/1000}`).join("  "));
console.log("queued:", queued.map(d=>`${d.id.slice(0,10)} gpu=${d.gpuMilli/1000} $${(Number(d.balance6)/1e6).toFixed(2)}`).join("  ") || "none");
