package contract

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// derive_vectors.json is generated by derive_reference.py, an independent reading of DERIVE.md. The Go rule every
// backend links must reproduce it exactly, and refuse exactly what it refuses.
type deriveVectors struct {
	ComponentHex string `json:"component_hex"`
	OK           []struct {
		Name         string            `json:"name"`
		Record       CatalogDerivation `json:"record"`
		BundleSha256 string            `json:"bundleSha256"`
		Mapping      CatalogMapping    `json:"mapping"`
	} `json:"ok"`
	Refused []struct {
		Name         string          `json:"name"`
		Record       json.RawMessage `json:"record"`
		ComponentHex string          `json:"component_hex"`
	} `json:"refused"`
}

func loadDeriveVectors(t *testing.T) deriveVectors {
	b, err := os.ReadFile("derive_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v deriveVectors
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	if len(v.OK) < 4 || len(v.Refused) < 7 {
		t.Fatalf("the vectors are too few to mean anything: %d ok, %d refused", len(v.OK), len(v.Refused))
	}
	return v
}

func TestDerivationMatchesTheIndependentReference(t *testing.T) {
	v := loadDeriveVectors(t)
	comp, _ := hex.DecodeString(v.ComponentHex)
	for _, c := range v.OK {
		m, b, err := MapCatalog(c.Record, comp)
		if err != nil {
			t.Fatalf("%s: %v", c.Name, err)
		}
		s := sha256.Sum256(b)
		if hex.EncodeToString(s[:]) != c.BundleSha256 || m != c.Mapping {
			t.Fatalf("%s: Go derived\n %+v\nthe reference\n %+v", c.Name, m, c.Mapping)
		}
		// and the bundle is a bundle the contract itself accepts, naming this component
		man, art, err := Parse(b)
		if err != nil || string(art) != string(comp) || man.World != DerivedWorld || man.Label != "" {
			t.Fatalf("%s: the derived bundle does not parse as the contract's own: %v", c.Name, err)
		}
	}
}

func TestIdentityDependsOnTheComponentAndPolicyOnly(t *testing.T) {
	v := loadDeriveVectors(t)
	// vectors 0-2: same component + policy under another catalog version / runtime: same AppID, new record
	a, b, c, d := v.OK[0].Mapping, v.OK[1].Mapping, v.OK[2].Mapping, v.OK[3].Mapping
	if a.AppID != b.AppID || a.AppID != c.AppID || a.RecordSha256 == b.RecordSha256 || a.RecordSha256 == c.RecordSha256 {
		t.Fatal("the catalog ref and pinned runtime must key the RECORD, not the AppID")
	}
	if d.AppID == a.AppID {
		t.Fatal("a different pinned policy must be a different AppID")
	}
}

func TestDerivationRefusesWhatTheReferenceRefuses(t *testing.T) {
	v := loadDeriveVectors(t)
	for _, c := range v.Refused {
		var rec CatalogDerivation
		comp, _ := hex.DecodeString(c.ComponentHex)
		if json.Unmarshal(c.Record, &rec) == nil {
			if _, _, err := MapCatalog(rec, comp); err == nil {
				t.Errorf("%s: accepted", c.Name)
			}
		}
	}
}

func TestADerivedBundleIsWhatTheContractCLIBuilds(t *testing.T) {
	v := loadDeriveVectors(t)
	comp, _ := hex.DecodeString(v.ComponentHex)
	r := v.OK[0].Record
	_, derived, err := MapCatalog(r, comp)
	if err != nil {
		t.Fatal(err)
	}
	// `bundle build -cpu C -mem M -vcpus V <component>`: world defaults to wasi:http, label to ""
	cli, err := Build(Manifest{ABI: ABI, World: "wasi:http", Artifact: Artifact{Kind: KindWasmComponent},
		Policy: r.Policy}, comp)
	if err != nil || string(cli) != string(derived) {
		t.Fatal("a derived bundle must be byte-identical to what a publisher builds with the contract's own tool")
	}
}
