// verifier/web/notices.mjs: the third-party notices of the browser bundle, generated from the EXACT inputs esbuild bundled
// (verifier/web/build.mjs metafile), never from package.json's dependency lists: what is in the file is what is noticed,
// including transitive packages (the Buffer stand-in brings base64-js and ieee754) and nested copies. Every third-party
// input must resolve to a package with a LICENSE file whose text is reproduced, or generation fails; a package whose
// package.json license field disagrees with its LICENSE file is stated as such (the file governs).
import fs from "node:fs";
import path from "node:path";

const licenseKind = (text) => (/Apache License/i.test(text) ? "Apache-2.0" : /Permission is hereby granted, free of charge/i.test(text) ? "MIT" : /Redistribution and use in source and binary forms/i.test(text) ? "BSD" : /BSD Zero Clause/i.test(text) ? "0BSD" : null);

// nearest package.json above a node_modules input, without leaving node_modules
function packageDirOf(rel) {
  let d = path.posix.dirname(rel);
  while (d.includes("node_modules")) {
    if (path.posix.basename(path.posix.dirname(d)) === "node_modules" || path.posix.basename(path.posix.dirname(path.posix.dirname(d))) === "node_modules" && path.posix.basename(path.posix.dirname(d)).startsWith("@")) return d;
    d = path.posix.dirname(d);
  }
  throw new Error(`no package directory for ${rel}`);
}
export function packagesOf(inputs, { repo }) {
  const third = new Map(), first = [];
  for (const rel of [...inputs].sort()) {
    if (!rel.includes("node_modules/")) { first.push(rel); continue; }
    const dir = packageDirOf(rel), abs = path.join(repo, dir);
    let pj; try { pj = JSON.parse(fs.readFileSync(path.join(abs, "package.json"), "utf8")); } catch (e) { throw new Error(`${rel}: no readable package.json at ${dir}`); }
    const key = `${pj.name}@${pj.version}`;
    if (!third.has(key)) {
      const lic = fs.readdirSync(abs).filter((f) => /^(LICEN[SC]E|COPYING)(\.|$)/i.test(f)).sort()[0];
      if (!lic) throw new Error(`${key} (${dir}) has no LICENSE file: its notice cannot be produced, so the bundle is not packaged (fail closed)`);
      const text = fs.readFileSync(path.join(abs, lic), "utf8");
      third.set(key, { name: pj.name, version: pj.version, declared: pj.license ?? null, dir, licenseFile: lic, licenseText: text, fileKind: licenseKind(text), files: [] });
    }
    third.get(key).files.push(rel);
  }
  return { third: [...third.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version)), first };
}
export function noticesFor(inputs, { repo, tool = null }) {
  const { third, first } = packagesOf(inputs, { repo });
  const out = [];
  out.push("# Third-party notices: the browser verifier bundle (verifier/web/dist/enclave-verifier-web.js)", "",
    "Generated by `verifier/web/build.mjs` from the exact inputs esbuild bundled, as recorded in `verifier/web/dist/MANIFEST.json`.",
    "Every package below contributes bytes to the bundle; nothing here is inferred from dependency lists. Regenerate after any",
    "dependency change: `verifier/web/reproduce.mjs` (under the strict integration command) refuses a stale file.", "");
  if (tool) out.push(`Build tool, not distributed in the bundle: ${tool}.`, "");
  out.push("## First-party (this repository)", "", ...first.map((f) => `- \`${f}\``), "");
  out.push("## Third-party", "");
  for (const p of third) {
    out.push(`### ${p.name}@${p.version}`, "");
    out.push(`- package.json license: ${p.declared ?? "(none declared)"}; LICENSE file: \`${p.licenseFile}\`${p.fileKind ? ` (${p.fileKind} text)` : ""}`);
    if (p.fileKind && p.declared && p.fileKind !== p.declared && !(p.fileKind === "BSD" && /BSD/.test(p.declared)))
      out.push(`- NOTE: package.json declares ${p.declared} but the LICENSE file is the ${p.fileKind} text; the file governs and is reproduced below.`);
    out.push(`- bundled files (${p.files.length}): ${p.files.map((f) => `\`${f.slice(p.dir.length + 1)}\``).join(", ")}`, "", "```", p.licenseText.replace(/\s+$/, ""), "```", "");
  }
  return out.join("\n");
}
