#!/bin/sh
# Write the app-binding evidence FROM a verify-app-binding.sh run directory. Every quoted line is cut from a file in
# it: good/ decoy/ truncated/ missing/, run.log (the harness's own scoring) and test-appbundle.out (local tests).
#
#   usage: write-app-binding-evidence.sh <workdir>
set -e
W=${1:?usage: write-app-binding-evidence.sh <workdir>}
for f in run.log good/P.evidence decoy/P.evidence truncated/P.evidence missing/P.evidence test-appbundle.out; do
  [ -r "$W/$f" ] || { echo "no $W/$f" >&2; exit 2; }
done
clean() { tr -d '\000' < "$1" | sed 's/\x1b\[[0-9;=?]*[A-Za-z]//g'; }
ev() { clean "$W/$1/P.evidence" | grep -ao "PLANE $2.*" | head -1 | sed 's/^/  /'; }
svsm() { clean "$W/$1/P.serial" | grep -ao "SVSM appid: .*" | sed 's/^/  /'; }
hashes() { clean "$W/$1/P.debugcon" | grep -ao 'Hash comparison [a-z]* for "[a-z]*"' | tr '\n' ' ' | sed 's/^/  /'; }
j() { python3 -c 'import json,sys
v=json.load(open(sys.argv[1]))
for k in sys.argv[2].split("."): v=v[k]
print(v)' "$W/$1/plane.manifest.json" "$2"; }
body() { sed -n 's/^RESULT app_body=\(.*\)/\1/p' "$W/$1/client.out" | head -1; }

cat <<EOF
The app a plane serves is the component of the bundle it ADMITTED
warden-host, 2026-09-24. Run $W, generated by m4/write-app-binding-evidence.sh from files in that directory.
Guest code at d094410c; hardware harness at 14eb1104 (copies with SHA256SUMS in $W/harness/). One plane, plane 2.
NOT independently reviewed: the reviewer is unavailable, and nothing after 39b5a5e4 has been reviewed.

WHAT WAS OPEN. The SVSM admits the BUNDLE - sha256 of all of it is the AppID in APP_TABLE - but the plane ran
/app.wasm, a separate file build-plane-guest.sh extracted at build time. The admitted bytes and the executed bytes
were two files tied only by the build: a genuine bundle beside a different /app.wasm would be admitted, named as
the bundle's app, and serve the other one.

WHAT CHANGED. planeinit reads /app.bundle ONCE into memory and stages exactly those bytes. After the SVSM accepts
them it cuts the component from the SAME buffer (guest/appbundle.h: the contract's framing, and the manifest must
begin by naming this component's sha256), and hands it to the runtime as a SEALED memfd - write, grow, shrink and
seal all sealed - at fd 3, which the runtime opens as /proc/self/fd/3. The image carries no /app.wasm.

GOOD: THE PLANE'S OWN CUT, AND WHAT IT SERVED
$(ev good "bundle=")
$(ev good "app=")
$(ev good "runtime_maps=")
  served: $(body good)
  launch digest $(j good igvm.launchDigest)

verify-plane.sh check 11 compares that component_sha256 with the CONTRACT's own extractor run on the bundle the
SVSM was built to admit, and requires no /app.wasm in the runtime's maps. The only file mapping outside the runtime
set is the sealed component itself, read-only.

DECOY: A DIFFERENT COMPONENT PLANTED WHERE THE OLD PLANEINIT RAN THE APP FROM
The same image plus /app.wasm = a component compiled with label DECOY. The SVSM tables are unchanged, so the old
planeinit would have been admitted and named as the bundle's app while serving DECOY.
$(ev decoy "stray_app_wasm=")
$(ev decoy "app=")
$(ev decoy "runtime_maps=")
  served: $(body decoy)     (the good plane served $(body good))

TRUNCATED: THE LAST 4 KiB OF THE BUNDLE MISSING, UNDER AN IGVM THAT COVERS THIS IMAGE AND THE GOOD RUN'S SVSM
$(hashes truncated)
$(ev truncated "bundle=")
$(ev truncated "refusal=")
$(ev truncated "serving=")
  SVSM console appid lines: $(svsm truncated | wc -l | tr -d ' ')
  launch digest $(j truncated igvm.launchDigest)

MISSING: NO /app.bundle IN THE IMAGE
$(hashes missing)
$(ev missing "bundle=")
$(ev missing "serving=")
$(ev missing "reason=")
  SVSM console appid lines: $(svsm missing | wc -l | tr -d ' ')

The reason line above says "the SVSM refused" although in this case the SVSM was never asked; the bundle line says
what actually happened. The wording was corrected after this run (this commit); the scoring used the bundle line.

In both negatives nothing was admitted (no SVSM appid line at all), nothing named, no key registered, no component
handed to a runtime, and the plane powered off. Their launch digests differ from the good plane's, so a verifier
pinning the good one rejects them first; the negatives isolate admission by construction.

THE HARNESS'S OWN SCORE (run.log)
$(grep -a "^PASS\|^FAIL\|^INFRA\|^M4b-app-binding:\|^exit=" "$W/run.log" | sed 's/^/  /')
  (G and D are each verify-plane.sh's eleven checks: $(grep -ac "^  PASS" "$W/run.log") inner PASS lines, $(grep -ac "^  FAIL" "$W/run.log") FAIL)

LOCAL TESTS (no guest), test-appbundle.out, at $(cat "$W/local-test.commit" 2>/dev/null || echo unrecorded)
$(grep -a "^PASS\|^FAIL\|^appbundle:" "$W/test-appbundle.out" | sed 's/^/  /')

WHAT THIS DOES NOT ESTABLISH

  ONE app on ONE plane, one guest. Nothing here is isolation BETWEEN apps; the second-plane blocker is unchanged.

  THE CUT IS THE PLANE'S OWN WORD. planeinit performs it and prints it; the hardware attests neither. It is worth
  relying on because planeinit is inside the initrd the launch measurement covers under step 2, and it fails closed.
  The report binds the AppID (the whole bundle), not the component hash; the component hash is recomputable from
  the bundle by anyone.

  THE SEALED MEMFD IS A KERNEL PROPERTY OF THE GUEST, not a hardware one. The admitted STAGED copy is frozen by the
  SVSM; the executed copy is the sealed memfd cut from the same buffer, in guest memory the guest kernel manages.

  THE MAPS CHECK IS ONE READING AT LOAD, as in the runtime-set evidence.

  NOT INDEPENDENTLY REVIEWED.
EOF
