#!/bin/sh
# Write the guestd evidence FROM a test-guestd.sh run directory: every quoted line is cut from a file in it.
#   usage: write-guestd-evidence.sh <passing workdir> <failed workdir>
set -e
W=${1:?usage: write-guestd-evidence.sh <passing workdir> <failed workdir>}; F=${2:?}
for f in run.log A.vm.json B.vm.json A.client B.client A-at-B.client B-at-A.client B.dead.json unit-tests.out commit; do
  [ -r "$W/$f" ] || { echo "no $W/$f" >&2; exit 2; }
done
[ -r "$F/run.log" ] || { echo "no $F/run.log" >&2; exit 2; }
j() { python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get(sys.argv[2],""))' "$W/$1" "$2"; }
vl() { grep -a '^VERDICT' "$W/$1" | cut -d' ' -f1-2; }
cat <<EOF
guestd: two apps, two SNP guests, through the /vms contract the supervisor already speaks
warden-host, 2026-09-24. Run $W at commit $(cat "$W/commit"), generated by m4/write-guestd-evidence.sh from files in
that directory (harness copies with SHA256SUMS in harness/). M4a's shape: ONE app per SNP guest, no planes, no SVSM.
NOT independently reviewed. Nothing in production starts guestd; it is disabled unless GUESTD_ENABLE=1.

THE TWO GUESTS, as guestd reported them (GET /vms/<id>)
  A  id $(j A.vm.json id)  appId $(j A.vm.json appId)
     status $(j A.vm.json status)  verdict $(j A.vm.json verdict)  vcpus $(j A.vm.json vcpus)  memMiB $(j A.vm.json memMiB)
     measurement $(j A.vm.json measurement)
  B  id $(j B.vm.json id)  appId $(j B.vm.json appId)
     status $(j B.vm.json status)  verdict $(j B.vm.json verdict)
     measurement $(j B.vm.json measurement)

VERIFIED FROM OUTSIDE guestd (m2/client.mjs, the M4a judge, with this test's OWN prediction from each bundle)
  A with A's expectations   $(vl A.client)     served $(sed -n 's/^RESULT app_body=//p' "$W/A.client")
  B with B's expectations   $(vl B.client)     served $(sed -n 's/^RESULT app_body=//p' "$W/B.client")
  A's expectations at B     $(vl A-at-B.client)
  B's expectations at A     $(vl B-at-A.client)
  The reports are VMPL0: M4a has no SVSM, and its isolation is the SNP guest boundary itself (own ASID, own
  memory-encryption key), not a privilege level. The judge says so in its reason and requires no boundary tuple.

A GUEST THAT DIED (its unit killed with SIGKILL)
  $(cat "$W/B.dead.json")

THE HARNESS'S OWN SCORE (run.log)
$(grep -a '^PASS\|^FAIL\|^guestd:\|^exit=' "$W/run.log" | sed 's/^/  /')

UNIT TESTS (-race), unit-tests.out
$(sed 's/^/  /' "$W/unit-tests.out")

THE FAILED RUN BEFORE THIS ONE, preserved: $F
$(grep -a '^PASS\|^FAIL\|^guestd:\|^exit=' "$F/run.log" | sed 's/^/  /')
  guestd's guests attested against guestd's own predictions (G2), but the TEST's independent prediction from the
  same bundle differed, so the independent client rejected both (G3, G4). The measured image carried the staged
  bundle's file MODE (guestd stages 0600), the builder's uid/gid and the host's library modes. Fixed in e280abf3
  (pack-initrd.sh); test-image-repro.sh R1 is that failing case. It is the reason G3 exists: guestd verifying
  its own guests could not have caught it.

WHAT THIS DOES NOT ESTABLISH
  - A DEPLOYMENT. No supervisor drove guestd; the test posted to it directly. No relay, no ledger, no lease.
  - A USER-VERIFIABLE MEASUREMENT beyond this host. The prediction is reproducible here from the bundle and this
    host's kernel, firmware, front, init and runtime; no domain release is published, so a remote verifier cannot
    yet recompute it (DEPLOYMENT-PATH.md, gate 2).
  - Anything about isolation from a malicious HOST beyond what SNP gives each guest, or about planes (M4b).
  - Parity: the guests get no secrets, config, egress, extra ports or GPU - guestd refuses deployments needing them.
  - Independent review.
EOF
