#!/bin/sh
# Write the runtime-set evidence FROM a verify-runtime-set.sh run directory. Every quoted line is cut from a file in
# that directory, never from a terminal: good/ (verify-plane.sh), changed/ and missing/ (the negative controls),
# run.log (the harness's own scoring), test-rtset.out and svsm-unit-tests.out (the local tests at the same code).
#
#   usage: write-runtime-set-evidence.sh <workdir>
set -e
W=${1:?usage: write-runtime-set-evidence.sh <workdir>}
for f in run.log good/P.evidence changed/P.evidence missing/P.evidence test-rtset.out svsm-unit-tests.out; do
  [ -r "$W/$f" ] || { echo "no $W/$f - run verify-runtime-set.sh and the local tests into it first" >&2; exit 2; }
done
clean() { tr -d '\000' < "$1" | sed 's/\x1b\[[0-9;=?]*[A-Za-z]//g'; }
ev() { clean "$W/$1/P.evidence" | grep -ao "PLANE $2.*" | head -1 | sed 's/^/  /'; }
evall() { clean "$W/$1/P.evidence" | grep -ao "PLANE $2.*" | sed 's/^/  /'; }
svsm() { clean "$W/$1/P.serial" | grep -ao "SVSM appid: .*" | sed 's/^/  /'; }
hashes() { clean "$W/$1/P.debugcon" | grep -ao 'Hash comparison [a-z]* for "[a-z]*"' | sed 's/^/  /'; }
j() { python3 -c 'import json,sys
v=json.load(open(sys.argv[1]))
for k in sys.argv[2].split("."): v=v[k]
print(v)' "$W/$1/plane.manifest.json" "$2"; }
rtset_of() { sed -n 's/.*runtime set     \([0-9a-f]*\) .*/\1/p' "$W/$1/build-guest.txt"; }
passes() { grep -a "$1" "$W/run.log" | sed 's/^ *//; s/^/  /'; }

cat <<EOF
The runtime SET, admitted whole: the interpreter and shared libraries are now inside admission
warden-host, 2026-09-24. Run $W, generated by m4/write-runtime-set-evidence.sh from files in that directory.
Guest code and encoder at 9d678395; the hardware harness at f3825d92, which changed no guest code, and whose files
are also copied with SHA256SUMS into $W/harness/.
Local tests re-run at $(cat "$W/local-test.commit" 2>/dev/null || echo "(unrecorded)"). One plane, plane 2. NOT independently reviewed: the reviewer is unavailable, and nothing
after 39b5a5e4 has been reviewed.

WHAT WAS OPEN. The plane runs /rt/ld-linux-x86-64.so.2 --library-path /rt /rt/wasmtime, and the SVSM admitted the
wasmtime ELF alone, so the interpreter, libc, libm and libgcc_s executed without the SVSM ever hashing them. Both
earlier evidence files (step2-measured-boot, plane-handshake-binding) say so, and stay scoped to that.

WHAT CHANGED. The runtime kind now admits ONE canonical encoding of every file in /rt (guest/rtset.h,
"enclave-runtime-set-v1": each member's name, length and bytes, in bytewise name order; a subdirectory, symlink or
any other non-file refuses the whole set). ENCLAVE_RUNTIME_SHA256 is sha256 of that encoding. The SVSM's code did
not change: it hashes bytes and compares digests, so a changed, missing, added or renamed file is refused by the
same comparison as any other artifact. One encoder, compiled into the guest and into the host tool that prints the
digest, so the digest the SVSM is built for and the bytes the plane stages cannot come from two implementations.

THE BUILD (good)
  IGVM            $(j good igvm.path)
                  sha256 $(j good igvm.sha256)
  launch digest   $(j good igvm.launchDigest)
  firmware        $(basename "$(j good firmware.path)"), sha256 $(j good firmware.sha256)
  svsm elf        $(j good svsm.elf)
  app id, plane 2 $(j good identity.ENCLAVE_APP_IDS | cut -d, -f2)
  runtime set     $(j good identity.ENCLAVE_RUNTIME_SHA256 | cut -d, -f2)
  runtime id      $(j good identity.ENCLAVE_RUNTIME_IDS | cut -d, -f2)

THE GOOD PLANE: THE SET, AS THE GUEST STAGED IT AND AS THE SVSM FROZE IT
$(evall good "runtime_member=")
$(ev good "runtime_set=")
$(ev good "runtime=")
$(ev good "status_after=")
$(ev good "whoami=")
and the SVSM's own console, which shares no code with the guest's lines:
$(svsm good)

12097 is ceil(49546136 / 4096): the SVSM hashed and froze the whole set. The wasmtime ELF alone was 11137 pages in
the handshake run, so a plane that staged the old artifact under the new label would show here.

WHAT THE RUNNING RUNTIME MAPPED, read from its own /proc maps before the front was started
$(ev good "runtime_maps=")

Every executable file mapping is an admitted member - by path AND by the inode that was encoded - and every one of
the 5 admitted ELFs is mapped; the check waits for the second condition so it cannot pass by looking before the
loader finished. /app.wasm is the only other file mapping: read-only data, see the limits below.

THE GOOD PLANE STILL DOES EVERYTHING IT DID (verify-plane.sh, all ten checks)
$(grep -a "^  PASS\|^  FAIL" "$W/run.log" | sed 's/^ *//; s/^/  /')
$(clean "$W/good/client.out" | grep -a "^VERDICT" | cut -d" " -f1-2 | sed 's/^/  /')
$(clean "$W/good/client.out" | grep -a "^RESULT gate=\|^RESULT app_requests_sent=\|^RESULT report_vmpl=" | sed 's/^/  /')

THE NEGATIVE CONTROLS: A CHANGED FILE AND A MISSING FILE CANNOT INHERIT THE IDENTITY
Each image differs from the good one ONLY in /rt. Each was launched under an IGVM whose measured table covers THAT
image, so the firmware verified it and let it boot, and whose SVSM is the good run's own binary built for the GOOD
set. So the only thing that can refuse it is admission - which is the claim.

  changed   RT_MUTATE=flip:libc.so.6 (one byte, in the middle)
            this image's set $(rtset_of changed)
            SVSM expects     $(j changed identity.ENCLAVE_RUNTIME_SHA256 | cut -d, -f2)
            svsm elf         $(j changed svsm.elf)
            launch digest    $(j changed igvm.launchDigest)
$(hashes changed)
$(ev changed "bundle=")
$(ev changed "runtime_set=")
$(ev changed "runtime=")
$(ev changed "refusal=")
$(ev changed "serving=")
$(ev changed "reason=")
  SVSM console:
$(svsm changed)

  missing   RT_MUTATE=drop:libgcc_s.so.1
            this image's set $(rtset_of missing)
            SVSM expects     $(j missing identity.ENCLAVE_RUNTIME_SHA256 | cut -d, -f2)
            svsm elf         $(j missing svsm.elf)
            launch digest    $(j missing igvm.launchDigest)
$(hashes missing)
$(ev missing "bundle=")
$(ev missing "runtime_set=")
$(ev missing "runtime=")
$(ev missing "refusal=")
$(ev missing "serving=")
$(ev missing "reason=")
  SVSM console:
$(svsm missing)

0x80001004 is E_DIGEST_MISMATCH, which appid.rs returns only after hashing the staged bytes and finding them unequal
to the compiled-in digest. The SVSM logged kind 0 (the bundle) and NO kind 1 in either negative: nothing of the set
was frozen, no whoami, no key registered, no document served; planeinit powered the domain off. The launch digests
also differ from the good plane's, so a verifier pinning the good one rejects these guests before admission is
reached - the negatives isolate the second layer by construction.

THE HARNESS'S OWN SCORE (run.log)
$(passes "^PASS\|^FAIL\|^INFRA")
$(grep -a "^M4b-runtime-set:\|^exit=" "$W/run.log" | sed 's/^/  /')

LOCAL TESTS AT THE SAME CODE (no guest), test-rtset.out and svsm-unit-tests.out
$(grep -a "^PASS\|^FAIL\|^rtset:" "$W/test-rtset.out" | sed 's/^/  /')
  SVSM appid unit tests: $(grep -a "test result" "$W/svsm-unit-tests.out" | sed 's/test result: //')

Among them: EVERY member of the set (6 of 6), not a sample, changes the digest when one bit flips, when it is one
byte short, and when it is absent; an added and a renamed file change it; a glibc-hwcaps subdirectory, a symlink,
a FIFO, an empty set and an oversized set are refused rather than skipped; and the maps check refuses a process
that maps an unadmitted executable, one whose member was renamed over after encoding (same bytes, new inode), and
one that never finished loading the set.

WHAT THIS DOES NOT ESTABLISH

  ONE app on ONE plane. Nothing here demonstrates isolation BETWEEN two apps on two planes, which is the
  requirement. The second-plane blocker stands unchanged: precondition 4's mechanism is unresolved (see
  HOST-CHANGE-PLAN.md), and no run is to be scored as isolation.

  THE COMPONENT IS NOT ADMITTED. What the runtime compiles and runs is /app.wasm, extracted from the bundle at
  BUILD time (build-plane-guest.sh). The admitted artifact is the bundle. Both are in the initrd the firmware
  verifies under step 2, so the component is inside the launch measurement - but the link between the admitted
  bundle and the executed component is the build, not admission. That is the next gap of the same shape; closing
  it means planeinit handing the runtime the component cut from the file it admitted.

  THE MAPS CHECK IS ONE READING AT LOAD. It sees what the loader mapped at start. A library opened later with
  dlopen would not be seen. None was observed for this command line on the host (LD_DEBUG=libs,files, one request
  served), which is an observation about this wasmtime build, not a guarantee.

  THE CHECK IS THE PLANE'S OWN WORD. planeinit performs it and prints it; the hardware does not attest it. It is
  worth relying on because planeinit is inside the initrd the launch measurement covers under step 2 and it fails
  closed (powers off) - the same standing as the VMPCK probe, and no stronger.

  THE FROZEN PAGES ARE A COPY. The SVSM hashes and freezes the STAGED copy of the set; the runtime executes the
  files in /rt. What ties them is that planeinit reads the same files it later starts, and that the maps check
  requires the executing file objects to be the ones it encoded (same inode). An in-place write to an /rt file
  between admission and start would need a writer inside the plane, and only measured code runs there; this is
  not enforced by hardware.

  THE LIBRARY LIST COMES FROM ldd ON THE BUILD HOST. The maps check is what guards it at runtime: a library the list
  missed would be an unadmitted executable mapping, and a listed one nothing loads would never be mapped - both stop
  the plane.

  THE STEP-2 FIXTURE WAS NOT RE-RUN. admitinit now stages the set as well (one meaning of ENCLAVE_RUNTIME_SHA256), and
  test-rtset check 13 shows its image carries the same set under the same digest, but verify-measured-boot.sh was
  not re-run on hardware. evidence/step2-measured-boot-2026-09-24.txt remains the record of the ELF-only fixture at
  its own revision.

  NOT INDEPENDENTLY REVIEWED.
EOF
