#!/bin/sh
# Write the catalog-mapping + domain-release evidence FROM a run-integration-tests.sh directory: every quoted line
# is cut from a file in it.
#   usage: write-integration-evidence.sh <workdir>
set -e
W=${1:?usage: write-integration-evidence.sh <workdir>}
for f in commit dirty contract.out guestd.out claim-gate.out domain-release.out image-repro.out; do
  [ -r "$W/$f" ] || { echo "no $W/$f" >&2; exit 2; }
done
cat <<EOF
Catalog-to-bundle mapping, guestd prefetch, and measurement reconstruction from a pinned domain release
warden-host, 2026-09-24. LOCAL tests only - no guest was launched for this evidence. Run $W, generated by
m4/write-integration-evidence.sh from files in that directory. Commit $(cat "$W/commit").
Working tree at the run: $( [ -s "$W/dirty" ] && sed 's/^/[/;s/$/]/' "$W/dirty" | tr '\n' ' ' || echo clean) (the runner itself, which runs the suites and touches none of the code under test)
NOT independently reviewed. Nothing here is deployed, published, merged or released; no chain state was read or
written.

SUITE EXIT CODES
$(for s in contract guestd claim-gate domain-release image-repro; do printf '  %-15s rc=%s\n' "$s" "$(cat "$W/$s.rc")"; done)

1. THE DERIVATION RULE (isolation/contract/catalog, enclave-catalog-bundle/1), against an independent reference
$(grep -a "^--- \|^ok" "$W/contract.out" | sed 's/^/  /')

2. GUESTD PREFETCH AND THE IMMUTABLE MAPPING STORE (go test -race)
$(grep -a "^--- \|^ok" "$W/guestd.out" | sed 's/^/  /')

3. THE SUPERVISOR CLAIM GATE (unchanged by this slice; re-run at this commit)
$(grep -a "^# \(tests\|pass\|fail\)" "$W/claim-gate.out" | sed 's/^/  /')

4. RECONSTRUCTION FROM A PINNED DOMAIN RELEASE - against LIVE measurements recorded by the guestd hardware run
$(grep -a "^PASS\|^FAIL\|^   \|^     \|^domain-release:" "$W/domain-release.out" | sed 's/^/  /')

5. IMAGE REPRODUCIBILITY (unchanged by this slice; re-run over the template/assembly split)
$(grep -a "^PASS\|^FAIL\|^image-repro:" "$W/image-repro.out" | sed 's/^/  /')

A FINDING RECORDED ON THE WAY (commit ba445c72). With the derivation first placed in isolation/contract (e4bab5b9),
build-app-guest.sh stopped reproducing those live measurements: the guest's front links the contract package, so
code no guest executes changed the front binary and moved EVERY per-app measurement. The rule now lives in
contract/catalog, which only the host-side guestd imports, and D6 above guards it. The lesson is that a measurement
is a function of the source revision of everything in the image - which is what the domain release pins.

WHAT THIS DOES NOT ESTABLISH
  - A deployment: the supervisor does not yet send a derivation record, the node-CVM-to-guestd channel (C7) and the
    ciphertext data path (C4) are not built, and no relay, ledger or lease was involved.
  - A PUBLISHED release: the release exists in a local run directory; a remote user cannot obtain it yet.
  - Which policy a catalog version pins (contract/catalog/DERIVE.md item 4): open, recorded as open.
  - Anything about the network gateway: the real CAR verifier was exercised against a synthetic loopback gateway.
  - Isolation between apps beyond what separate SNP guests give (M4a); nothing about planes (M4b).
  - Independent review.
EOF
