#!/bin/sh
# Write the verifier-hardening + guestd-control/1 evidence FROM a run-integration-tests.sh directory. Every quoted
# line is cut from a file in it.
#   usage: write-control-evidence.sh <workdir>
set -e
W=${1:?usage: write-control-evidence.sh <workdir>}
for f in commit dirty guestd.out domain-release.out control.out contract.out claim-gate.out image-repro.out; do
  [ -r "$W/$f" ] || { echo "no $W/$f" >&2; exit 2; }
done
cat <<EOF
The verifier needs a pin and one snapshot; guestd-control/1 authenticates the control channel
warden-host, 2026-09-24. LOCAL tests only - no guest was launched for this evidence. Run $W, generated by
m4/write-control-evidence.sh from files in that directory. Commit $(cat "$W/commit").
Working tree at the run: $( [ -s "$W/dirty" ] && sed 's/^/[/;s/$/]/' "$W/dirty" | tr '\n' ' ' || echo clean)
NOT independently reviewed. Nothing deployed, published, merged, released or installed; no production secret or
setting exists for this channel yet.

SUITE EXIT CODES
$(for s in contract guestd claim-gate domain-release image-repro control; do printf '  %-15s rc=%s\n' "$s" "$(cat "$W/$s.rc")"; done)

1. THE VERIFIER HELPER (review points on af33b25c)
  Acceptance needs an explicit pinned release; inspection is a separate, labelled mode; the release AND the bundle
  are snapshotted once; the runtime identity is emitted from the verified snapshot; malformed arguments fail.
$(grep -a "^PASS\|^FAIL\|^domain-release:" "$W/domain-release.out" | sed 's/^/  /')
  Unpinned verification is self-consistency only - a manifest rewritten to match a tampered file has it too (D3) -
  and is never presented as trust.

2. guestd-control/1 (m4/guestd/auth.go), unit and interop tests under -race
$(grep -a "^--- .*\(Credentials\|Unauthenticated\|Handshake\|Replay\|TamperedRequest\|Instances\|Expire\|Bounded\|KeyFile\|JSClient\)" "$W/guestd.out" | sed 's/^/  /')
$(grep -a "interop:" "$W/guestd.out" | sed 's/^ */  /' | cut -c1-600)
  (all guestd tests: $(grep -ac "^--- PASS" "$W/guestd.out") PASS, $(grep -ac "^--- FAIL" "$W/guestd.out") FAIL)

3. guestd-control/1 through the real binary's flags (test-guestd-control.sh)
$(grep -a "^PASS\|^FAIL\|^     client\|^guestd-control:" "$W/control.out" | sed 's/^/  /')

THE TRUST BOOTSTRAP, as built. One principal per guestd: whoever holds its pairing key (generated once, 0600, never
overwritten; refused if others can read it). The handshake is bound to a per-start instance id and a single-use
nonce, and guestd proves the key back. Every request is MAC'd over session, sequence, method, exact target and
body, with a replay window; every answer is signed. Sessions expire, and a restart ends them all.

WHAT THIS DOES NOT ESTABLISH
  - Delivery of the key into the node CVM, and the transport bridge (vsock, or slirp to loopback): not built. guestd
    still listens on loopback only, with or without a key (C6 above).
  - Protection from the host's root: the host runs guestd and its guests and can stop them regardless. The key
    stops other local users and processes, other VMs on a future bridge, replay and cross-instance confusion.
  - Any security property of a GUEST: the supervisor must still verify each guest's attestation itself; nothing a
    guest's security rests on is taken from this channel.
  - The supervisor using control-client.mjs: not wired.
  - Independent review.
EOF
