#!/bin/sh
# Write the plane-binding evidence FROM a verify-plane.sh run directory.
#
# WHY GENERATED. The hand-written first version of this file quoted a VERDICT/RESULT block and four negatives that
# existed only in my terminal, while the file said every quoted line was cut from the run's own files. The claims
# were true and the reviewer reproduced them offline, but a reader could not check them - the same defect I had
# already caught once in the step-2 evidence and written a generator to prevent. verify-plane.sh now saves every
# client transcript, and this cuts from those.
#
#   usage: write-plane-evidence.sh <workdir>
set -e
W=${1:?usage: write-plane-evidence.sh <workdir>}
[ -r "$W/client.out" ] || { echo "no client.out in $W - run verify-plane.sh, which saves the transcripts" >&2; exit 2; }
pl() { tr -d '\000' < "$W/P.evidence" | sed 's/\x1b\[[0-9;=?]*[A-Za-z]//g' | grep -ao "PLANE $1.*" | head -1 | sed 's/^/  /'; }
dom() { tr -d '\000' < "$W/P.serial" | sed 's/\x1b\[[0-9;=?]*[A-Za-z]//g' | grep -ao "DOM $1.*" | head -1 | sed 's/^/  /'; }
res() { grep -a "^$1" "$W/client.out" | head -1 | sed 's/^/  /'; }
neg() { printf '  %-22s %s\n' "$1" "$(sed -n 's/^VERDICT \(.*\)/\1/p' "$W/$2" | head -1 | cut -c1-96)"; }
j() { python3 -c 'import json,sys
d=json.load(open(sys.argv[1]))
ks=sys.argv[2].split("."); v=d
for k in ks: v=v[k]
print(v)' "$W/plane.manifest.json" "$1" 2>/dev/null || echo "(absent)"; }

cat <<EOF
The handshake key, bound by the measured SVSM: a serving plane domain, attested end to end
warden-host, $(date +%Y-%m-%d). Run $W, generated by m4/write-plane-evidence.sh. Every quoted line is cut from a
file in that directory - the client transcripts are client.out and neg-*.out, the guest's are P.evidence and
P.serial - so a reader can check each one rather than take it from a terminal I no longer have.

WHAT WAS MISSING UNTIL NOW. Step 2 closed the artifact binding, but the key in report_data was a synthetic
91-byte value admitinit made up. So "the report binds this domain's transport key" was true of a test vector and
not of a handshake anyone could perform. This closes it.

THE SHAPE. The front mints its TLS key, REGISTERS it with the SVSM once, and afterwards sends only a nonce. The
SVSM computes report_data[0:32] = Bind2(that key, the nonce, the RuntimeID compiled into its own measured image)
and fills report_data[32:64] from APP_TABLE indexed by the CALLING PLANE. Neither half is a field of the request.

THE BUILD
  IGVM            $(j igvm.path)
                  sha256 $(j igvm.sha256)
  launch digest   $(j igvm.launchDigest)
  firmware        $(basename "$(j firmware.path)"), sha256 $(j firmware.sha256)
  app id, plane 2 $(j identity.ENCLAVE_APP_IDS | cut -d, -f2)
  runtime id      $(j identity.ENCLAVE_RUNTIME_IDS | cut -d, -f2)

THE PLANE ADMITS, PROVES ITS CONFINEMENT, AND ONLY THEN SERVES
$(pl "boot=")
$(pl "status_before=")
$(pl "bundle=")
$(pl "runtime=")
$(pl "status_after=")
$(pl "whoami=")

whoami is the SVSM naming the plane from its own compiled table. planeinit powers the domain OFF instead of
serving if either admission is refused: a domain that served after a refusal would answer /attest with a T0
document, substituting a weaker claim for a stronger one, which a client cannot detect unless it pins the tier.

CONFINEMENT, IN THE KERNEL'S OWN WORDS - not inferred from an errno
$(pl "tsm_report_core=")
$(for id in 0 1 2 3; do pl "vmpck${id}="; pl "vmpck${id}_reason="; done)
$(pl "boundary=")

The image CARRIES tsm_report and sev-guest deliberately: leaving them out would make "no report interface" a
property of the packaging, which no verifier can check. But ENODEV alone does NOT establish a withheld key -
sev-guest registers with module_platform_driver_probe (sev-guest.c:711) and __platform_driver_probe returns
-ENODEV whenever nothing binds, which also happens when there is no sev-guest platform device at all or when the
kernel sees no SNP, and this guest decides snp=1 from CPUID, the hardware's word rather than the kernel's. So the
probe reads /dev/kmsg and reports the reason: "Empty VMPCK%d communication key" is arch/x86/coco/sev/core.c:1569,
printed at KERN_ERR, which loglevel=3 keeps off the console but never out of the ring buffer. Each probe names
its OWN key, and EVERY key the kernel will hand out is tried: get_vmpck switches on 0..3 and vmpck_id is a plain
module parameter, so a guest can ask for any of them - which is why the SVSM's copy_with_no_vmpck clears
0..VMPL_MAX. An earlier version of this probe tried only 0 and 2, evidencing half the space while the text
claimed the plane holds none. planeinit powers off if ANY load succeeds.

THE FRONT REGISTERS THE KEY IT WILL USE
$(dom "runtime ")
$(dom "plane ")
$(dom "serving ")

THE VERDICT, from $W/client.out
$(res "VERDICT")
$(res "RESULT gate=")
$(res "RESULT app_requests_sent=")
$(res "RESULT doc_key_matches_handshake=")
$(res "RESULT report_vmpl=")
$(res "RESULT abi=")
$(res "RESULT boundary=")
$(res "RESULT measurement=")

and from the same transcript, the verifier's own evidence lines:
$(grep -a "^evidence: report_data binds\|^evidence: AMD signature chain\|^evidence: report is from VMPL\|^evidence: report_data\[32:64\]" "$W/client.out" | sed 's/^/  /')

VERIFIER-SIDE NEGATIVES, same live domain, each transcript saved
$(neg "expecting VMPL0" neg-vmpl0.out)
$(neg "a different app id" neg-appid.out)
$(neg "a different runtime" neg-runtime.out)
$(neg "a different measurement" neg-measurement.out)

THE FORMAT ALLOWLIST IS A GATE, and it caught this fixture's own new format first: the first run was rejected
"unknown attestation format sev-snp-svsm-plane-v1", gate closed. m2/judge.mjs now carries a table naming each
format and what it IMPLIES, so admitting one states its constraints rather than widening a condition.
sev-snp-svsm-plane-v1 requires ABI/2 and a NON-ZERO VMPL: at VMPL0 nothing is above the guest, and under ABI/1
the binding folds in no runtime identity, so either way the document would claim an authority it lacks.

WHAT THIS DOES NOT ESTABLISH

  THE FORMAT LABEL IS UNAUTHENTICATED. The independent reviewer relabelled this document
  format=sev-snp-guest-domain-v1 and it still attests - a weaker claim, not a wider acceptance. Nothing in the
  document proves the SVSM composed report_data; what establishes that is the MEASUREMENT the caller pins, since
  the digest covers the SVSM and its tables. The same applies to the boundary tuple: any field the guest writes
  is a guest claim, so the tuple was deliberately NOT extended with a vmpck field - a VMPL0 guest could write it
  as easily as it can set a floor. Under THIS digest, planes hold no VMPCK, and the kmsg lines above are the run
  evidence for that digest.

  THE PROPERTY IS ENFORCED BY RECOMPUTATION, not by the document agreeing with itself. judge.mjs recomputes
  Bind2 over the key of the handshake it performed, so RESULT doc_key_matches_handshake is only informational.
  The reviewer ran the negative that shows this: the same document judged with a SWAPPED handshake key is
  rejected, "report_data does not bind". A replayed nonce is rejected too.

  A KEY ROTATION IMPLIES A RECLAIM. REGISTER_KEY is once per admission and the front refuses to start if the
  slot is taken, which is the right failure, but it means rotating a domtls key requires a reclaim cycle rather
  than a re-registration. Nothing here exercises that.

  The runtime image admitted is the wasmtime ELF only; its interpreter and shared libraries are not admitted, so
  the executing bytes include unadmitted code.

  ONE app on ONE plane. Nothing here demonstrates isolation BETWEEN two apps on two planes, which is the
  requirement. No second plane has been brought up; the preconditions are in svsm/README.md, and the kernel
  change and reboot they need are Steven's call.
EOF
