#!/bin/sh
# Write the control-client hardening + supervisor transport evidence FROM a run-integration-tests.sh directory.
#   usage: write-transport-evidence.sh <workdir>
set -e
W=${1:?usage: write-transport-evidence.sh <workdir>}
for f in commit dirty guestd.out supervisor.out control.out claim-gate.out; do
  [ -r "$W/$f" ] || { echo "no $W/$f" >&2; exit 2; }
done
cat <<EOF
guestd-control client hardening, and the supervisor reaching guestd only over it (default off)
warden-host, 2026-09-24. LOCAL tests only - no guest launched, no key provisioned anywhere, nothing installed or
activated. Run $W, generated by m4/write-transport-evidence.sh from files in that directory.
Commit $(cat "$W/commit"). Working tree at the run: $( [ -s "$W/dirty" ] && sed 's/^/[/;s/$/]/' "$W/dirty" | tr '\n' ' ' || echo clean)
NOT independently reviewed.

SUITE EXIT CODES
$(for s in contract guestd claim-gate domain-release image-repro control supervisor; do [ -r "$W/$s.rc" ] && printf '  %-15s rc=%s\n' "$s" "$(cat "$W/$s.rc")"; done)

1. THE REPORTED RACE, KEPT AS A GENUINE FAILURE AGAINST THE CLIENT IT WAS REPORTED ON (a40f1019)
$(grep -a "control-client-a40f1019.mjs:" "$W/guestd.out" | sed 's/^ */  /' | cut -c1-400)
$(grep -a "^--- .*RaceIsReal" "$W/guestd.out" | sed 's/^/  /')
  The old client made TWO handshakes for two concurrent first requests, and checked the first request's authentic
  answer against the second session's key. That is an availability failure, not an authentication bypass.

2. THE FIXED CLIENT UNDER CHAOS (a wrapper in front of the REAL server; counts from the server)
$(grep -a "^--- .*Chaos" "$W/guestd.out" | sed 's/^/  /')
$(grep -a "\.\./control-client.mjs:" "$W/guestd.out" | sed 's/^ */  /' | fold -w 200 | sed '2,$s/^/  /')

3. THE SUPERVISOR'S OWN vmReq, THROUGH GUESTD_TRANSPORT_SELFTEST, AGAINST THE REAL SERVER
$(grep -a "^--- .*Supervisor" "$W/guestd.out" | sed 's/^/  /')
$(grep -a "transport_test.go:[0-9]*: seam" "$W/guestd.out" | sed 's/^ */  /' | cut -c1-260)

4. EVERYTHING ELSE AT THE SAME COMMIT
  guestd: $(grep -ac "^--- PASS" "$W/guestd.out") PASS, $(grep -ac "^--- FAIL" "$W/guestd.out") FAIL (-race)
  supervisor-driving repository tests (flag off): $(grep -a "^# \(tests\|pass\|fail\|skipped\)" "$W/supervisor.out" | tr '\n' ' ')
  control channel through the real binary: $(grep -a "^guestd-control:" "$W/control.out")
  claim gate: $(grep -a "^# \(pass\|fail\)" "$W/claim-gate.out" | tr '\n' ' ')

WHAT THIS DOES NOT ESTABLISH
  - A running deployment: no bridge carries the channel across the node CVM boundary, no pairing key is delivered
    into a node, and the supervisor sends no derivation record on spawn (there is no published per-version policy
    to pin, and the catalog policy decision is separate). Catalog launches therefore still stop at guestd's refusal.
  - The encrypted data path (C4) and a per-deployment attestation endpoint returning the guest's own document.
  - Any property of the guests themselves; the host's root remains outside what the pairing key protects against.
  - Independent review.
EOF
