from pathlib import Path
import os,subprocess,json,time
w=Path(__file__).resolve().parent;r=Path('/home/steven/Projects/enclave-v100-isolation');rt=Path(os.environ.get('TEST_RUNTIME','/home/steven/enclave-prod/release-f674c047/template/rt'));label=os.environ.get('TEST_LABEL','native');cpu=Path(os.environ.get('TEST_CPU',str(rt/'backends/libggml-cpu.so')))
for i in range(2):
 alias=Path(f'/dev/shm/enclave-shielded-shm/card-{i+2}');target=Path(f'/dev/shm/enclave-shield-v100/card-{i}')
 if not alias.exists() or not alias.samefile(target) or alias.stat().st_size != 67108864:raise RuntimeError(f'Prepare an existing 64-MiB worker ring alias first: {alias} -> {target}; do not truncate live rings')
env={**os.environ,'LD_LIBRARY_PATH':str(rt),'BACKENDS':str(cpu)+':'+os.environ.get('TEST_BACKEND',str(w/'backend-native/libggml-shielded.so')),'SHIELDED_SO_FOR_STATS':os.environ.get('TEST_BACKEND',str(w/'backend-native/libggml-shielded.so')),'ENCLAVE_GGML_EXTRA_BUFTS':'0','SHIELDED_PROFILE':'1','SHIELDED_VERBOSE':'1','SHIELDED_PHASE_TRACE':'1','SHIELDED_CALIB':str(r/'metal/shielded-overlay/calib/qwen3.8-27b-mtp-q4-vl-gguf.calib'),'SHIELDED_WORKERS':'127.0.0.1|9501|0|16642998272|/dev/shm/enclave-shielded-shm/card-2|67108864\n127.0.0.1|9502|0|16642998272|/dev/shm/enclave-shielded-shm/card-3|67108864','SHIELDED_MAX_M':'64','SHIELDED_REFILL_BATCH':'64','SHIELDED_POOL_DEPTH':'64','SHIELDED_REFILL_THREADS':os.environ.get('TEST_REFILL','8'),'SHIELDED_SPLIT_COLS':'1','SHIELDED_OVERLAP_VERIFY':'1','SHIELDED_WEIGHT_BUDGET_FRAC':'.95','OMP_NUM_THREADS':os.environ.get('TEST_THREADS','8'),'THREADS':os.environ.get('TEST_THREADS','8'),'K':'1','ENCLAVE_GGML_N_RS_SEQ':'1','WARM':'1','LABEL':label}
(w/(label+'-config.json')).write_text(json.dumps({k:v for k,v in env.items() if k not in os.environ or v!=os.environ[k] or k in {'LD_PRELOAD','SHIELDED_REFILL_VECTOR_CRT','SHIELDED_CPU_MAIN','SHIELDED_CPU_HELPER','SHIELDED_CPU_REST'}},indent=2))
with (w/(label+'.json')).open('w') as out,(w/(label+'.err')).open('w') as err:
 p=subprocess.run(['/home/steven/enclave-bench/b27/bench-spec2','/home/steven/Projects/enclave-models/qwen3.8-27b-mtp-q4-vl-gguf/Qwen3.8-27B-UD-Q4_K_XL.gguf','Explain in one paragraph why the sky is blue, then list three related phenomena.',os.environ.get('TEST_STEPS','64')],env=env,stdout=out,stderr=err,timeout=400)
print('returncode',p.returncode);print((w/(label+'.json')).read_text());raise SystemExit(p.returncode)
