// GENERATED by scripts/gen-abi.mjs from the Foundry build of contracts/SessionVault.sol. Do not edit.
export const sessionVaultAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_usdc",
        "type": "address",
        "internalType": "contract ISVToken"
      },
      {
        "name": "_book",
        "type": "address",
        "internalType": "contract ISVBook"
      },
      {
        "name": "_router",
        "type": "address",
        "internalType": "contract ISVRouter"
      },
      {
        "name": "_ka",
        "type": "address",
        "internalType": "contract ISVKeyAttestations"
      },
      {
        "name": "_maxVault6",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ACT_CREATE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_FUND",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_PUBLISH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_REFUND",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_SET_ACTIVE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_SET_APPREF",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_SET_CONFIG",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_SET_MAXRATE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ACT_SET_SHARES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ADOPT_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "CALL_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "END_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ENV_PROD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ENV_STAGING",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EXTEND_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "GRANT_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PROMOTE_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "RELEASE_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REVOKE_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SETENV_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TERMINATE_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TOPUP_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "WITHDRAW_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "adopt",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "environment",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "book",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISVBook"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "close",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epoch",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "nonce",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "action",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "args",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "deadline",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "x",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "y",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "r",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sv",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "result",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "extend",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "factory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "free",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantDigest",
    "inputs": [
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct SessionVault.Grant",
        "components": [
          {
            "name": "label",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "preset",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "sessionKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actions",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "apps",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "environments",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "budget",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spendPerPeriod",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "periodSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "opsPerPeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxFeePerOp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxAppFeePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxRatePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "measurement",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "grantNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signBefore",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "held",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "env",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "promoted",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "createdBy",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isLive",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "keyAttestations",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISVKeyAttestations"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "locked6",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxVault6",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "open",
    "inputs": [
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct SessionVault.Grant",
        "components": [
          {
            "name": "label",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "preset",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "sessionKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actions",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "apps",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "environments",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "budget",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spendPerPeriod",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "periodSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "opsPerPeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxFeePerOp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxAppFeePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxRatePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "measurement",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "grantNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signBefore",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "ownerSig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "openWithDeposit",
    "inputs": [
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct SessionVault.Grant",
        "components": [
          {
            "name": "label",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "preset",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "sessionKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actions",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "apps",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "environments",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "budget",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spendPerPeriod",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "periodSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "opsPerPeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxFeePerOp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxAppFeePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxRatePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "measurement",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "grantNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signBefore",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "ownerSig",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "validAfter",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "validBefore",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "authSig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ownerCall",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "ret",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ownerNonceUsed",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "promote",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "app",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "publisher",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "appRef",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "configCid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "versionLabel",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "isPublic",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "release",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeAll",
    "inputs": [
      {
        "name": "alsoWithdraw",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "router",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISVRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "seqOf",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "",
        "type": "uint192",
        "internalType": "uint192"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sessionIdOf",
    "inputs": [
      {
        "name": "sessionKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "grantNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sessionOf",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "s",
        "type": "tuple",
        "internalType": "struct SessionVault.Session",
        "components": [
          {
            "name": "keyHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "measurement",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actions",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "envs",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "state",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "anyApp",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "balance6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "spent6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "perPeriod6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maxFee6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maxAppFeeHour6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maxRateHour6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "periodStart",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "period",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "opsPerPeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "periodSpent6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "periodOps",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "live",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "apps",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setEnvironment",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "environment",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "terminate",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "terminateBySession",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "deadline",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "x",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "y",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "r",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sv",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "topUp",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "topUpWithAuthorization",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "validAfter",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "validBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "authSig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "usdc",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISVToken"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "opNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signBefore",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Extended",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HeldSet",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "env",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "createdBy",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Promoted",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "promoted",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "appRef",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "configCid",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Released",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RevokedAll",
    "inputs": [
      {
        "name": "epoch",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "withdrawn6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SessionEnded",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "refund6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fee6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SessionOp",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "nonce",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "action",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "argsHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "amount6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fee6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "result",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SessionOpened",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "keyHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "actions",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "envs",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "budget6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "label",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ToppedUp",
    "inputs": [
      {
        "name": "sid",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "amount6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fromWallet",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "amount6",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AllowanceLeft",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AppFeeTooHigh",
    "inputs": [
      {
        "name": "perHour",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "AppNotAllowed",
    "inputs": [
      {
        "name": "appId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadNonce",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPolicy",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadRef",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadTarget",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BudgetExceeded",
    "inputs": [
      {
        "name": "need",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "have",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "EnvNotAllowed",
    "inputs": [
      {
        "name": "env",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "Exists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeTooHigh",
    "inputs": [
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "Initialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Insolvent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LabelMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoAttestation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoContract",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NonceUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAllowed",
    "inputs": [
      {
        "name": "action",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFactory",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotHeld",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotLive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotMine",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OverCap",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "PeriodLimit",
    "inputs": [
      {
        "name": "need",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "left",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RateCapOutOfRange",
    "inputs": [
      {
        "name": "rate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RateLimit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Reentrant",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownAction",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownEnvironment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongEnvironment",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "env",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "FundRateTooLow",
    "inputs": [
      {
        "name": "rate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "feeTimesTwo",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LeaseUnsettled",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  }
];

export const sessionVaultFactoryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "usdc",
        "type": "address",
        "internalType": "contract ISVToken"
      },
      {
        "name": "book",
        "type": "address",
        "internalType": "contract ISVBook"
      },
      {
        "name": "router",
        "type": "address",
        "internalType": "contract ISVRouter"
      },
      {
        "name": "keyAttestations",
        "type": "address",
        "internalType": "contract ISVKeyAttestations"
      },
      {
        "name": "maxVault6",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createVault",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "vault",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "implementation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract SessionVault"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isVault",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openFor",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct SessionVault.Grant",
        "components": [
          {
            "name": "label",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "preset",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "sessionKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actions",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "apps",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "environments",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "budget",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spendPerPeriod",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "periodSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "opsPerPeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxFeePerOp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxAppFeePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxRatePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "measurement",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "grantNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signBefore",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "ownerSig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "vault",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "openWithDepositFor",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct SessionVault.Grant",
        "components": [
          {
            "name": "label",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "preset",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "sessionKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actions",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "apps",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "environments",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "budget",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spendPerPeriod",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "periodSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "opsPerPeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxFeePerOp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxAppFeePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxRatePerHour",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "measurement",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "grantNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signBefore",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "ownerSig",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "validAfter",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "validBefore",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "authSig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "vault",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "sid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "vaultFor",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "VaultCreated",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "vault",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  }
];

export const usdcAbi = [
  {
    "type": "function",
    "name": "name",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "type": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "version",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "type": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "balanceOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "a",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "type": "uint256"
      }
    ]
  }
];

export const addressBookAbi = [
  {
    "type": "function",
    "name": "addr",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "type": "address"
      }
    ]
  }
];

export const ledgerDelegateAbi = [
  {
    "type": "function",
    "name": "setDelegate",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "delegate",
        "type": "address"
      },
      {
        "name": "allowed",
        "type": "bool"
      }
    ],
    "outputs": []
  },
  {
    "type": "event",
    "name": "DelegateSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "delegate",
        "type": "address",
        "indexed": true
      },
      {
        "name": "allowed",
        "type": "bool",
        "indexed": false
      }
    ]
  }
];
