#!/usr/bin/env python3
"""Generate fixtures/harness-gen.c from the production payload source (no hand-written replica): extracts, verbatim, (a) write_all,
(b) pads_judge_fd, (c) the shipment reception block of pads_receiver (from the retry check 'have it already?' through the
final anchor_rx_close(c)), and wraps them with bounded FAKE boundaries: fsync/write/rename/dir_sync/open-under-dir, the shipment
header check, the ack signer, hex/random helpers, OUT capture, and the real SHA-256 (shielded-sha256.h) behind the
anchor_sha256_* names. Any marker missing in the candidate makes generation FAIL (so the harness cannot silently drift)."""
import re, sys, hashlib
from pathlib import Path
SRC = Path(sys.argv[1]); DEST = Path(sys.argv[2]); s = SRC.read_text()
def func(name):
    m = re.search(r"^static int %s\([^)]*\) \{\n" % name, s, re.M); assert m, "missing " + name
    i = m.start(); j = s.index("\n}\n", i) + 3; return s[i:j]
write_all = func("write_all"); judge = func("pads_judge_fd")
a = s.index("        struct stat st;\n        {   /* have it already?"); assert a > 0
end = "        anchor_rx_close(c);\n"
b = s.index(end + "    }\n    anchor_rx_exited();\n    return NULL;\n}", a); block = s[a:b + len(end)]
for must in ("anchor_sha256_init(&ah)", "anchor_sha256_update(&ah", "anchor_sha256_final(&ah, stream_sha)", "stream_ok", "pads_judge_fd(name, fd, ack, sizeof ack, stream_sha, bytes)", "pads_judge_fd(name, hfd, ack, sizeof ack, NULL, bytes)", "dir_sync(g_pads_dir)", "rename(tmp, fin)"):
    assert must in block, "candidate block lacks: " + must
prelude = r'''/* GENERATED by gen_harness.py from ../anchor_payload.c (source sha256 @@SHA@@) - do not edit; regenerate. */
#define _GNU_SOURCE
#include "shielded-sha256.h"
#include "anchor_rxctl.h"
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <signal.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <unistd.h>
#define SH_OK 0
#define SH_ERR_IO (-5)
typedef enum { ANCHOR_NAME_REFUSED = 0, ANCHOR_NAME_SHIPMENT = 1, ANCHOR_NAME_PREFIX = 2 } anchor_name_class;
typedef struct { uint8_t opaque[128]; } anchor_sha256_ctx;
typedef struct { int valid; uint8_t seed_id[16]; char seed_id_hex[33]; char name[65]; uint8_t calib[32]; } ack_identity;
static ack_identity g_ack; static pthread_mutex_t g_ack_mu = PTHREAD_MUTEX_INITIALIZER;
static unsigned char g_tsk[64], g_psk[32]; static char g_pads_dir[512];
/* ---- captured output + fault injection (bounded fakes) ---- */
static char g_out[65536]; static size_t g_out_n; static int g_padack_lines;
static void OUT(const char *fmt, ...) { char l[1024]; va_list ap; va_start(ap, fmt); vsnprintf(l, sizeof l, fmt, ap); va_end(ap); if (!strncmp(l, "PADACK ", 7)) g_padack_lines++; size_t k = strlen(l); if (g_out_n + k + 2 < sizeof g_out) { memcpy(g_out + g_out_n, l, k); g_out_n += k; g_out[g_out_n++] = '\n'; g_out[g_out_n] = 0; } }
static struct { int fsync_fail, rename_fail, dirsync_fail, sign_fail, header_fail, truncate_after_fsync; long write_fail_after; int write_fd; int short_writes; int eintr_every; } inj;
static long g_write_calls, g_short_writes, g_eintr_injected, g_sha_updates;
static int fake_fsync(int fd) { if (inj.fsync_fail) { errno = EIO; return -1; } int rc = fsync(fd); if (rc == 0 && inj.truncate_after_fsync > 0) { struct stat st; if (fstat(fd, &st) == 0) (void)!ftruncate(fd, st.st_size - inj.truncate_after_fsync); } return rc; }
static ssize_t fake_write(int fd, const void *p, size_t n) {
    if (fd == inj.write_fd) { g_write_calls++;
        if (inj.eintr_every && g_write_calls % inj.eintr_every == 0) { g_eintr_injected++; errno = EINTR; return -1; }   /* write_all must retry */
        if (inj.short_writes && n > 1) { n = 1 + (size_t)(g_write_calls % 7919) % (n - 1); g_short_writes++; }              /* partial write: write_all must continue */
        if (inj.write_fail_after >= 0) { if (inj.write_fail_after == 0) { errno = ENOSPC; return -1; } if ((long)n > inj.write_fail_after) n = (size_t)inj.write_fail_after; inj.write_fail_after -= (long)n; } }
    return write(fd, p, n); }
static int fake_rename(const char *a, const char *b) { if (inj.rename_fail) { errno = EIO; return -1; } return rename(a, b); }
static int dir_sync(const char *dir) { (void)dir; if (inj.dirsync_fail) { errno = EIO; return -1; } return 0; }
static int fake_open(const char *p, int flags, ...) { int mode = 0; if (flags & O_CREAT) { va_list ap; va_start(ap, flags); mode = va_arg(ap, int); va_end(ap); } int fd = open(p, flags, mode); if (fd >= 0 && (flags & O_CREAT)) inj.write_fd = fd; return fd; }
#define fsync(fd) fake_fsync(fd)
#define write(fd, p, n) fake_write(fd, p, n)
#define rename(a, b) fake_rename(a, b)
#define open(...) fake_open(__VA_ARGS__)
static int sh_pads_shipment_check_fd(int fd, const uint8_t *seed_id, const uint8_t *sk, const uint8_t *calib, uint64_t *i0, uint64_t *cnt) { (void)fd; (void)seed_id; (void)sk; (void)calib; if (inj.header_fail) return -1; *i0 = 0; *cnt = 64; return SH_OK; }
static int g_sign_calls; static int sh_pads_request_sign(const unsigned char *sk, const char *kind, const char *const *fields, size_t n, const char *nonce_hex, uint8_t sig[64]) { (void)sk; (void)kind; (void)fields; (void)n; (void)nonce_hex; g_sign_calls++; if (inj.sign_fail) return -1; memset(sig, 0x5a, 64); return SH_OK; }
static void sh_pads_bin2hex(const uint8_t *in, size_t n, char *out) { static const char *h = "0123456789abcdef"; for (size_t i = 0; i < n; i++) { out[2*i] = h[in[i] >> 4]; out[2*i+1] = h[in[i] & 15]; } out[2*n] = 0; }
static void randombytes(unsigned char *p, size_t n) { for (size_t i = 0; i < n; i++) p[i] = (unsigned char)(i * 7 + 1); }
static void anchor_sha256_init(void *c) { sha_init((sha256_ctx *)c); }
static void anchor_sha256_update(void *c, const uint8_t *m, size_t n) { g_sha_updates++; sha_update((sha256_ctx *)c, m, n); }
static void anchor_sha256_final(void *c, uint8_t out[32]) { sha_final((sha256_ctx *)c, out); }
static int anchor_sha256_fd(int fd, uint8_t out[32], uint64_t *bytes) { uint8_t *buf = malloc(1 << 20); sha256_ctx c; sha_init(&c); uint64_t off = 0; for (;;) { ssize_t r = pread(fd, buf, 1 << 20, (off_t)off); if (r < 0) { if (errno == EINTR) continue; free(buf); return -1; } if (r == 0) break; sha_update(&c, buf, (size_t)r); off += (uint64_t)r; } free(buf); sha_final(&c, out); if (bytes) *bytes = off; return 0; }
/* ---- VERBATIM candidate text follows ---- */
'''.replace("@@SHA@@", hashlib.sha256(s.encode()).hexdigest())
main = r'''
/* ---- driver: one shipment through the verbatim block ---- */
typedef struct { int fd; unsigned long long total; size_t maxchunk; int shortstop; unsigned seed; } feeder;
static void *feed(void *a) { feeder *f = (feeder *)a; unsigned long long sent = 0, limit = f->shortstop ? f->total / 2 : f->total; unsigned s = f->seed; char *buf = malloc(f->maxchunk ? f->maxchunk : 1);
    while (sent < limit) { s = s * 1103515245u + 12345u; size_t n = 1 + (s >> 8) % f->maxchunk; if (n > limit - sent) n = (size_t)(limit - sent); for (size_t i = 0; i < n; i++) { s = s * 1103515245u + 12345u; buf[i] = (char)(s >> 16); } if (write_all(f->fd, buf, n) != 0) break; sent += n; }
    free(buf); shutdown(f->fd, SHUT_WR); return NULL; }
static void receive_one(int c, const char *name, unsigned long long bytes, anchor_name_class kind) {
    anchor_rx_reset();
    if (!anchor_rx_set_active(c)) abort();
    char tmp[700], fin[700]; snprintf(tmp, sizeof tmp, "%s/.%s.tmp", g_pads_dir, name); snprintf(fin, sizeof fin, "%s/%s", g_pads_dir, name);
    for (int once = 0; once < 1; once++) {   /* the candidate block runs inside pads_receiver's accept loop: its `continue` = next connection */
@@BLOCK@@
    }
}
int main(int argc, char **argv) {
    unsigned long long bytes = 5000000; size_t maxchunk = 70000; int shortstop = 0, prefix = 0, retry = 0; const char *dir = "/tmp/pad-ack-gen";
    inj.write_fail_after = -1; inj.write_fd = -1;
    for (int i = 1; i < argc; i++) { if (!strncmp(argv[i], "feed=", 5)) bytes = strtoull(argv[i] + 5, 0, 10); else if (!strncmp(argv[i], "chunk=", 6)) maxchunk = strtoul(argv[i] + 6, 0, 10); else if (!strcmp(argv[i], "short=1")) shortstop = 1; else if (!strcmp(argv[i], "prefix=1")) prefix = 1; else if (!strcmp(argv[i], "retry=1")) retry = 1; else if (!strcmp(argv[i], "fsyncfail=1")) inj.fsync_fail = 1; else if (!strcmp(argv[i], "renamefail=1")) inj.rename_fail = 1; else if (!strcmp(argv[i], "dirsyncfail=1")) inj.dirsync_fail = 1; else if (!strcmp(argv[i], "signfail=1")) inj.sign_fail = 1; else if (!strcmp(argv[i], "headerfail=1")) inj.header_fail = 1; else if (!strncmp(argv[i], "truncate=", 9)) inj.truncate_after_fsync = atoi(argv[i] + 9); else if (!strncmp(argv[i], "writefail=", 10)) inj.write_fail_after = atol(argv[i] + 10); else if (!strcmp(argv[i], "shortwrites=1")) inj.short_writes = 1; else if (!strncmp(argv[i], "eintr=", 6)) inj.eintr_every = atoi(argv[i] + 6); else if (!strncmp(argv[i], "dir=", 4)) dir = argv[i] + 4; }
    signal(SIGPIPE, SIG_IGN); snprintf(g_pads_dir, sizeof g_pads_dir, "%s", dir); mkdir(dir, 0700);
    g_ack.valid = 1; strcpy(g_ack.seed_id_hex, "557e318293c4fb303ced57779e179a38"); strcpy(g_ack.name, "pixel");
    const char *name = prefix ? "prefix.kv" : "557e318293c4fb303ced57779e179a38-0-64.pads"; const anchor_name_class kind = prefix ? ANCHOR_NAME_PREFIX : ANCHOR_NAME_SHIPMENT;
    char fin[700]; snprintf(fin, sizeof fin, "%s/%s", g_pads_dir, name); unlink(fin);
    if (retry) {   /* the shipment is already stored: deterministic content, the held-descriptor path must answer H with a PADACK */
        int f = open(fin, O_WRONLY | O_CREAT | O_TRUNC, 0600); unsigned s = 0x51; char *buf = malloc(4096); for (unsigned long long off = 0; off < bytes; ) { size_t n = bytes - off < 4096 ? (size_t)(bytes - off) : 4096; for (size_t i = 0; i < n; i++) { s = s * 1103515245u + 12345u; buf[i] = (char)(s >> 16); } write_all(f, buf, n); off += n; } free(buf); close(f); inj.write_fd = -1; }
    int sv[2]; if (socketpair(AF_UNIX, SOCK_STREAM, 0, sv) != 0) return 2;
    feeder fe = { sv[1], retry ? 0 : bytes, maxchunk, shortstop, 0x51 }; pthread_t th; pthread_create(&th, NULL, feed, &fe);
    receive_one(sv[0], name, bytes, kind);            /* the block closes sv[0] itself */
    pthread_join(th, NULL);
    char resp = '?'; { char rb[8]; ssize_t n; while ((n = read(sv[1], rb, sizeof rb)) > 0) resp = rb[n - 1]; } close(sv[1]);   /* G (go) then the verdict: keep the LAST byte */
    struct stat st; int published = stat(fin, &st) == 0; char tmpp[700]; snprintf(tmpp, sizeof tmpp, "%s/.%s.tmp", g_pads_dir, name); int tmp_left = access(tmpp, F_OK) == 0;
    uint8_t fsha[32] = {0}; uint64_t fbytes = 0; if (published) { int f = open(fin, O_RDONLY); anchor_sha256_fd(f, fsha, &fbytes); close(f); }
    char fh[65]; sh_pads_bin2hex(fsha, 32, fh); char ackline[600] = ""; { const char *p = strstr(g_out, "PADACK "); if (p) { size_t k = strcspn(p, "\n"); if (k >= sizeof ackline) k = sizeof ackline - 1; memcpy(ackline, p, k); ackline[k] = 0; } }
    printf("{\"resp\":\"%c\",\"published\":%d,\"tmp_left\":%d,\"published_bytes\":%llu,\"published_sha\":\"%s\",\"padack_lines\":%d,\"padack\":\"%s\",\"sign_calls\":%d,\"sha_updates\":%ld,\"write_calls\":%ld,\"short_writes\":%ld,\"eintr_injected\":%ld,\"out\":\"", resp, published, tmp_left, (unsigned long long)fbytes, fh, g_padack_lines, ackline, g_sign_calls, g_sha_updates, g_write_calls, g_short_writes, g_eintr_injected);
    for (size_t i = 0; i < g_out_n; i++) { char ch = g_out[i]; if (ch == '"' || ch == '\\') putchar('\\'); if (ch == '\n') { putchar('\\'); putchar('n'); } else putchar(ch); }
    printf("\"}\n"); if (published) unlink(fin); if (tmp_left) unlink(tmpp); return 0;
}
'''
out = prelude + write_all + "\n" + judge + "\n" + main.replace("@@BLOCK@@", "\n".join(l[4:] if l.startswith("    ") else l for l in block.split("\n")))
DEST.write_text(out); print("generated harness-gen.c from source sha256", hashlib.sha256(s.encode()).hexdigest()[:16], "block lines", block.count("\n"))
