// Regenerates src/abi.ts from the Foundry build of contracts/SessionVault.sol,
// so the SDK's ABI can never drift from the contract (run after `forge build`).
// The vault's errors and SessionVaultLib's are merged: library reverts surface
// through the vault, and a caller decodes one error set.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../../../contracts/foundry/out/SessionVault.sol");
const read = (n) => JSON.parse(readFileSync(join(out, `${n}.json`), "utf8")).abi;

const vault = read("SessionVault");
const lib = read("SessionVaultLib");
const factory = read("SessionVaultFactory");
const seen = new Set(vault.filter((e) => e.type === "error").map((e) => e.name));
const merged = [...vault, ...lib.filter((e) => e.type === "error" && !seen.has(e.name))];

const usdc = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "version", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
];
const book = [
  { type: "function", name: "addr", stateMutability: "view", inputs: [{ name: "key", type: "bytes32" }], outputs: [{ type: "address" }] },
];

const body = `// GENERATED by scripts/gen-abi.mjs from the Foundry build of contracts/SessionVault.sol. Do not edit.
export const sessionVaultAbi = ${JSON.stringify(merged, null, 2)} as const;

export const sessionVaultFactoryAbi = ${JSON.stringify(factory, null, 2)} as const;

export const usdcAbi = ${JSON.stringify(usdc, null, 2)} as const;

export const addressBookAbi = ${JSON.stringify(book, null, 2)} as const;
`;
writeFileSync(join(here, "../src/abi.ts"), body);
// the relay ships as plain JS files (relay/deploy.sh copies them by name)
writeFileSync(join(here, "../../../relay/sessions-abi.mjs"), body.replace(/ as const;/g, ";"));
console.log(`[gen-abi] ${merged.length} vault entries, ${factory.length} factory entries -> src/abi.ts, relay/sessions-abi.mjs`);
